portfolio/portfolio/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^',include('varun.urls'))
]

portfolio/varun/urls.py
from django.conf.urls import url
from . import views

app_name='varun'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^submit_form/add/$',views.SubmitView,name='submit_form'),
    url(r'^thank_you/$',views.ThankView,name='thank_you'),
    url(r'^error/$',views.ErrorView,name='error'),

]

portfolio/varun/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class Query(models.Model):
    name     = models.CharField(max_length=50)
    email    = models.CharField(max_length=30)
    question = models.CharField(max_length=500)
    city     = models.CharField(max_length=20)

    def __str__(self):
        return self.name

portfolio/varun/forms.py
from django import forms


class SubmitForm(forms.Form):
    name      = forms.CharField(label='name',max_length=50,widget=forms.TextInput(
                 attrs={
                     'class' : 'form-control',
                     'placeholder':'Name'
                 }
    ))
    email     = forms.EmailField(label='email',max_length=50,widget=forms.EmailInput(
                 attrs={
                     'class' : 'form-control',
                     'placeholder':'Email'
                 }
    ))
    question  = forms.CharField(label='question',max_length=50,widget=forms.TextInput(
                 attrs={
                     'class' : 'form-control',
                     'placeholder':'Question'
                 }
    ))
    city      = forms.CharField(label='city',max_length=50,widget=forms.TextInput(
                 attrs={
                     'class' : 'form-control',
                     'placeholder':'City'
                 }
    ))

portfolio/varun/views.py
from django.shortcuts import render,redirect
from .models import Query
from .forms import SubmitForm
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib import messages
# Create your views here.
def index(request):
    form=SubmitForm()
    return render(request,'varun/varun.html',{'form' : form})


def SubmitView(request):
        form=SubmitForm()
        if request.method == 'POST':
             form=SubmitForm(request.POST)
             if form.is_valid():
                 name=request.POST.get('name')
                 email=request.POST.get('email')
                 question=request.POST.get('question')
                 city=request.POST.get('city')
                 query_obj=Query(name=name,email=email,question=question,city=city)
                 query_obj.save()
                 messages.success(request , 'Thanks. Your response has been submitted')
                 return redirect('varun:thank_you')

             else:
                 messages.error(request, 'Oops! There has been a problem Kindly check data')
                 return redirect('varun:error')


        else:
            form=SubmitForm()
        return render(request,'varun/varun.html',{
            'form' : form
            })

    #return HttpResponse("<h3>hey</h3>")

def ThankView(request):
    return render(request,'varun/thank_you.html')

def ErrorView(request):
    return render(request,'varun/error.html')


















'''

def SubmitView(request):
    if request.method=="POST":
        qr=Query()
        qr.name=request.POST.get('name')
        qr.email=request.POST.get('email')
        qr.question=request.POST.get('question')
        qr.city=request.POST.get('city')
        qr.save()
    return HttpResponseRedirect(reverse('varun:index'))

    #        form=SubmitForm(request.POST)
    #    if form.isvalid():
    """
            name=request.POST.get('name')
            email=request.POST.get('email')
            question=request.POST.get('question')
            city=request.POST.get('city')
            query_obj=Query(name=name,email=email,question=question,city=city)
            query_obj.save()
    """

#    else:
#        form=SubmitForm()

#    return render(request,'varun/form.html',{
#    'form' : form
#    })
'''

'''
def SubmitView(request):
    if request.method == 'POST':
        form=SubmitForm(request.POST)
        if form.is_valid():

            return HttpResponseRedirect('varun:index')

    else:
        form=SubmitForm()
        return render(request, 'varun/varun.html', {'form': form})
'''
'''
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            question = form.cleaned_data['question']
            city = form.cleaned_data['city']
            query_obj=Query(name=name,email=email,question=question,city=city)   '''

portfolio/varun/templates/varun/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'varun/varun.css' %}"/>

<div class="jumbotron" style="padding: 0px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'varun:index' %}" style="font-size:1.5em">Varun Gupta</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
  aria-controls="navbarNavAltMarkup"
   aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
    <div class="navbar-nav" >
      <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('about');" href="#">About</a>
     <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('skills');" href="#">Skills</a>
     <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('resume');" href="#">Resume</a>
     <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('projects');" href="#">Projects</a>
     <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('contact');" href="#">Contact</a>
    </div>

</div>
</nav>
<div id="xyz" style="color: white;
  text-align: center;
   position: relative;">
         <img src="{% static 'varun/images/back8.jpeg' %}" class="ig" style="z-index:-20"/>


         {% block message %}
         {% endblock %}

  </div>

</div>

portfolio/varun/templates/varun/error.html


{% extends 'varun/base.html' %}



{% block message %}

{% if messages %}
<div class="row" style="position:absolute;top:50%;left:50%;transform: translate(-50%,-50%);z-index:500">
 <div class="col-sm-12 ">
 {% for message in messages %}

   <div{% if message.tags == "error" %} class="alert alert-danger alert-dismissable" {% endif %}>
   <a href="{% url 'varun:index' %}" class="close" data-dismiss="alert" aria-label="close">&nbsp;&nbsp;&nbsp;&times;</a>
     <strong>Error&nbsp;&nbsp;</strong>{{ message }}</div>

 {% endfor %}
</div>
</div>
{% endif %}


{% endblock %}

portfolio/varun/templates/varun/thank_you.html


{% extends 'varun/base.html' %}



{% block message %}

{% if messages %}
<div class="row" style="position:absolute;top:50%;left:50%;transform: translate(-50%,-50%);z-index:500">
 <div class="col-sm-12 ">
 {% for message in messages %}

   <div{% if message.tags == "success" %} class="alert alert-success alert-dismissable" {% endif %}>
   <a href="{% url 'varun:index' %}" class="close" data-dismiss="alert" aria-label="close">&times;</a>
     <strong>Success!</strong>
   {{ message }}</div>
 {% endfor %}
</div>
</div>
{% endif %}

{% endblock %}

portfolio/varun/templates/varun/varun.html

<html>
<head>
	<title>Varun's Website</title>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	 {% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'varun/varun.css' %} ">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script type="text/javascript" src="{% static 'varun/varun.js' %} "></script>
</head>
<body>



<div class="container-fluid" style="background-color: #262626;">
										<div class="jumbotron" style="padding: 0px;">
										<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
										  <a class="navbar-brand" href="" style="font-size:1.5em">Varun Gupta</a>
										  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
											aria-controls="navbarNavAltMarkup"
											 aria-expanded="false" aria-label="Toggle navigation">
										    <span class="navbar-toggler-icon"></span>
										  </button>
										  <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
										    <div class="navbar-nav" >
													<a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('about');" href="#">About</a>
												 <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('skills');" href="#">Skills</a>
												 <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('resume');" href="#">Resume</a>
												 <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('projects');" href="#">Projects</a>
												 <a class="nav-item nav-link" onclick="return false;" onmousedown="autoScrollTo('contact');" href="#">Contact</a>
										    </div>

										</div>
										</nav>
										<div id="xyz" style="color: white;
											text-align: center;
										   position: relative;">
										         <img src="static/varun/images/back7.jpeg" class="ig" style="z-index:-20"/>
										         <div style="position:absolute;top:50%;left:50%;transform: translate(-50%,-50%);z-index:500">
															<h4 style="font-style:italic;font-family:Helvetica">Hello,I am</h4>
															<h1 style="font-weight:700;font-size:6em;text-transform:uppercase;font-family:proxima-nova">Varun Gupta</h1>

														<div>
																<button type="button" onclick="return false;" onmousedown="autoScrollTo('about');" class="btn btn-dark btn-lg" id="arrow">Read More About Me</button>
														</div>
											</div>

										</div>



    <div id ="main_section">

 	      <div id="about" class ="black_text" style="position:relative;">


			      <div class="row">
 			          <div class="col-sm-12">
 	       				    <h4>Something you should know</h4>
								</div>
						</div>
						<div class="row">
			          <div class="col-sm-5 col-xs-5">
			      		    <img src="static/varun/images/IMG_20170319_234438.jpg" id="bg-img" class="rounded-circle" alt="Responsive image"/>
			          </div>
			    			<div class="col-sm-7 col-xs-7">
			      		    <div class="row">
			                  <div class="col-sm-12 col-xs-12" style="margin-bottom: 20px;">
			                      <h3>Field Of Interests</h3>
			         					</div>
			       				</div>
			       				<div class="row">
			          		    <div class="col-sm-4 col-xs-4 interest">Machine Learning
			          				</div>
			          				<div class="col-sm-4 col-xs-4 interest">Data Analysis
			          				</div>
			          				<div class="col-sm-4 col-xs-4 interest">Full Stack Development
			          				</div>
		           			</div>
		           			  <p>Hi, I am Varun Gupta. Currently I am persuing B.tech in Computer Science and Engineering with specialization in
											   <strong>Big Data Analytics.</strong></p>
						    </div>
		       </div>
        </div>

        <div id="skills" class ="white_text">
            <div class="row">
                <div class="col-sm-12 col-xs-12">
             		    <h4>Checkout my skills</h4>
        				</div>
    				</div>
        		<div class="row">
		    		    <div class="col-sm-4 col-xs-4">
			    			    <p style="vertical-align: 50%">Skills:-</p>
								</div>
								<div class="col-sm-8 col-xs-8">
			    			    <div id=skills_box >
										    	<div class="skill_boxes" style="border:2px solid #24366D;background-color: #3C5CBA;">Html</div>
										    	<div class="skill_boxes" style="border:2px solid #388E3C;background-color: #145A32;">CSS</div>
										    	<div class="skill_boxes" style="border:2px solid #641E16;background-color: #E74C3C;">Javascript</div>
										    	<div class="skill_boxes" style="border:2px solid #512E5F;background-color: #8E44AD;">Android</div>
										    	<div class="skill_boxes" style="border:2px solid #A04000;background-color: #E67E22;">c++</div>
										    	<div class="skill_boxes" style="border:2px solid #9B5D73;background-color: #C38B8B;">c</div>
										    	<div class="skill_boxes" style="border:2px solid #143A52;background-color: #6E828A;">java</div>
										    	<div class="skill_boxes" style="border:2px solid #FFFFC1;background-color: #FFD2A5;">Python</div>
										    	<div class="skill_boxes" style="border:2px solid #512E5F;background-color: #900C3F;">Machine Learning</div>
										    	<div class="skill_boxes" style="border:2px solid #24366D;background-color: #3C5CBA;">hadoop</div>
										    	<div class="skill_boxes" style="border:2px solid #DC4712;background-color: #EE712B;">Data analysis</div>
										    	<div class="skill_boxes" style="border:2px solid #476269;background-color: #40A798;">sql</div>
									 </div>
							 </div>
						</div>
        </div>

        <div id="resume" class ="black_text">
	    	    <div class="row">
		    		    <div class="col-sm-12 col-xs-12">
		    				    <h4>You can see my resume here...!!</h4>
								</div>
		        </div>
		 				<p>Download my resume <a href="#" style="color:black;text-decoration: underline"><strong>here</strong></a></p>
				</div>


				<div id="projects" class="white_text">
				    <div class="row">
		  			    <div class="col-sm-12 col-xs-12">
			  				    <h4>Projects</h4>
	    				  </div>
   				  </div>
	 					<div class="row" style="margin:5px">
									  			    <div class="col-sm-6 test" style="background-color:rgba(255,162,52,.8); border:3px solid black;">
										   				    <div clas="row">
							                        <div class="col-sm-12" >
							                            <h3 style="font-family: Abril Fatface;padding-top:5px">Android Project</h3>
																			</div>
																	</div>
															<p style="font-family: FF Meta Serif">In this project I created an basic android app which implements
															signup and login functionality using database mongodb.Take a look at source code of my github Repository
														by clicking down below.</p>
															<button type="button" class="btn btn-dark git" style="margin-bottom:5px;">
																<a target="_blank" href="https://github.com/varun1907/Bunk-Poll">View On Github</a></button>

									   					</div>


											 					<div class="col-sm-6 test" style="background-color:#40A798;border:3px solid black">
												 				    <div clas="row">
														 				    <div class="col-sm-12">
																 				    <h3 style="font-family: Abril Fatface ;padding-top:5px">Computer Vision</h3>
																				</div>
												 						</div>
												 					  <p style="font-family: FF Meta Serif">In this project I worked on image recognzation stuff using
																			<strong>opencv</strong> library of python like extracting out frames from the video,converting them to
																				gray scale and other performing other functionalities of the library
																		</p>
														        <button type="button" class="btn btn-dark git" style="margin-bottom:5px;">
																			<a href="#">View On Github</a></button>
											 					</div>


										 					<div class="col-sm-6 test" style="background-color:#3C5CBA;border:3px solid black">
											 					   <div clas="row">
																	     <div class="col-sm-12">
																			     <h3 style="font-family: Abril Fatface ;padding-top:5px">Data Analysis</h3>
																			 </div>
											 						 </div>
											 					 	<p style="font-family: FF Meta Serif"> In this project I performed Data Analysis on Dataset of fifa 2017 players taken from kaggle.
							Data was in csv format containing 50+ attributes of 17000+ players.Using Python I performed analysis like
							.Want to know more take a look at my <strong>Github</strong> Repository
																  </p>
							 									 	 <button type="button" class="btn btn-dark git" style="margin-bottom:5px;"><a target="_blank" href="https://github.com/varun1907/kaggleFifaDataAnalysis">
																		 View On Github</a></button>
										 					</div>


		        </div>
		   </div>

       <div id="contact" class ="white_text">
           <div class="col-sm-12 col-xs-12">
                <h4>Any Queries</h4>
          </div>
    	    <div class="row">
			        <div class="col-sm-6 col-xs-6">
			            <p style="text-align:left">Contact :- <b>+917060915094</b></p>
				    			<p style="text-align:left">Hire me :- Mail me at <b>varun1907@gmail.com</b></p>
			    		</div>
			    		<div class="col-sm-6 col-xs-6">
			    		    <div class="row">
			    				    <div class="col-sm-12 col-xs-12"><h3>Questions?Submit Your Response<h3></div>
			    				</div>
									<div id ="contact_form" style="padding-right: 5px;margin-bottom: 5px">
													<form method="post" action="{% url 'varun:submit_form' %}" role="form" stype>
										     {% csrf_token %}
									    <div class="form-row">
										      <div class="form-group col-md-6" >
										        <label for="{{ form.name.id_for_label }}">Name</label>
														{{ form.name }}
										      </div>
									      <div class="form-group col-md-6">
										        <label for="{{ form.email.id_for_label }}">Email</label>
														{{ form.email }}
										      </div>
										    </div>
										    <div class="form-group">
										      <label for="{{ form.question.id_for_label }}">Query</label>
													{{ form.question }}
										    </div>
										    <div class="form-row">
										      <div class="form-group col-md-6">
										        <label for="{{ form.city.id_for_label }}">City</label>
														{{ form.city }}
										      </div>
												</div>
										    <button type="submit" class="btn btn-primary">Submit</button>
										</form>

				         </div>
		        </div>
		    </div>
    </div>
</div>



    <footer id="the_footer" class ="black_text">
					<a href="https://www.facebook.com/varun.gupta.3785373" target="_blank" class="fa fa-facebook"></a>
					<a href="#" target="_blank" class="fa fa-linkedin"></a>
					<a href="https://plus.google.com/u/0/109531738164712542209" target="_blank" class="fa fa-google"></a>
					<a href="https://www.instagram.com/varun3900/?hl=en" target="_blank" class="fa fa-instagram"></a>
					<a href="https://github.com/varun1907" target="_blank" class="fa fa-github"></a>
				   <p>&copy;Varun Gupta  2017</p>

    </footer>
    <button type="button" onclick="toTop()" class="btn btn-dark"  style="position:fixed;bottom:0;right:0;">Go To top</button>

</div>


</body>
</html>